.TH VERIFICAR_CLAVE 1 "Aug 04, 2015"
.SH NAME
verificar_clave \- Herramienta para comprobar la clave por defecto.
.SH SYNOPSIS
.B verificar_clave
.SH DESCRIPTION
.B VERIFICAR_CLAVE
Verifica que la clave de un usuario en particular no esté siendo utilizada. 
En caso afirmativo, se informa mediante un mensaje al inicio de sesión, 
notificado en el escritorio.
.SH SEE ALSO
https://github.com/daltomi/verificar_clave
.PP
.SH AUTHOR
UPSTREAM:  Daniel T. Borelli
.PP
Este manual ha sido escrito por Mauro <mauro@krutt.org>, para Huayra
GNU/Linux (pero puede ser utilizado por otros).
